/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 01-Dec-2021 9:15:14 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */


/* Drop Tables */

DROP TABLE IF EXISTS Dia CASCADE
;

DROP TABLE IF EXISTS Domicilio CASCADE
;

DROP TABLE IF EXISTS Aceptado CASCADE
;

DROP TABLE IF EXISTS Favorito CASCADE
;

DROP TABLE IF EXISTS Horario CASCADE
;

DROP TABLE IF EXISTS Medidasseguridad CASCADE
;

DROP TABLE IF EXISTS Negocio CASCADE
;

DROP TABLE IF EXISTS Opinion CASCADE
;

DROP TABLE IF EXISTS Reservacion CASCADE
;

DROP TABLE IF EXISTS Servicios CASCADE
;

DROP TABLE IF EXISTS Sucursal CASCADE
;

DROP TABLE IF EXISTS sucursalmedidasSeguridad CASCADE
;

DROP TABLE IF EXISTS sucursalservicios CASCADE
;

DROP TABLE IF EXISTS Tiponegocio CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

/* Create Tables */

CREATE TABLE Dia
(
    DiaID serial       NOT NULL,
    Dia   varchar(255) NULL
)
;

CREATE TABLE Domicilio
(
    Calle          varchar(255) NULL,
    Ciudad         varchar(255) NULL,
    Colonia        varchar(255) NULL,
    Estado         varchar(255) NULL,
    Municipio      varchar(255) NULL,
    Numeroexterior smallint     NULL,
    Numerointerior smallint     NULL,
    Pais           varchar(255) NULL,
    DomicilioID    serial       NOT NULL
)
;

CREATE TABLE Aceptado
(
    AceptadoID serial       NOT NULL,
    Aceptado   varchar(255) NULL
)
;
INSERT INTO Aceptado
VALUES (1, 'Aceptado'),
       (2, 'Rechazado'),
       (3, 'En espera')
;

CREATE TABLE Favorito
(
    SucursalID        serial       NOT NULL,
    Correoelectronico varchar(255) NOT NULL
)
;

CREATE TABLE Horario
(
    Horarioapertura time without time zone NULL,
    Horariocierre   time without time zone NULL,
    HorarioID       serial                 NOT NULL,
    DiaID           serial                 NOT NULL,
    SucursalID      serial                 NOT NULL
)
;
INSERT INTO Dia
VALUES (1, 'LUNES'),
       (2, 'MARTES'),
       (3, 'MIERCOLES'),
       (4, 'JUEVES'),
       (5, 'VIERNES'),
       (6, 'SABADO'),
       (7, 'DOMINGO'),
       (8, 'TODOS')
;


CREATE TABLE Medidasseguridad
(
    MedidasseguridadID serial       NOT NULL,
    Medidaseguridad    varchar(255) NULL
)
;
INSERT INTO Medidasseguridad
VALUES (1, 'SANADISTANCIA'),
       (2, 'TOMADETEMPERATURA'),
       (3, 'TRABAJADORESCONPROTECCION'),
       (4, 'GELDESINFECTANTE'),
       (5, 'CUBREBOCASOBLIGATORIO'),
       (6, N'AGUAYJABONENBANIOS'),
       (7, 'DESINFECCIONDESUPERFICIES'),
       (8, 'ENTRADASYSALIDASSEPARADAS'),
       (9, 'SANITIZACIONDELESTABLECIMIENTO'),
       (10, 'SANADISTANCIAMARCADAENFILAS'),
       (11, 'OTRA')
;

CREATE TABLE Negocio
(
    CorreoelectronicoUsuario varchar(255) NOT NULL,
    Facebook                 varchar(255) NULL,
    Fotoperfil               bytea        NULL,
    Instagram                varchar(255) NULL,
    Nombrenegocio            varchar(255) NULL,
    Telefono                 varchar(255) NULL,
    Whatsapp                 varchar(255) NULL,
    NegocioID                serial       NOT NULL,
    TiponegocioID            serial       NOT NULL,
    Correoelectronico        varchar(255) NULL
)
;

CREATE TABLE Opinion
(
    Calificacion      smallint                    NULL,
    Comentario        varchar(255)                NULL,
    Fechaopinion      timestamp without time zone NULL,
    Correoelectronico varchar(255)                NOT NULL,
    SucursalID        serial                      NOT NULL
)
;

CREATE TABLE Reservacion
(
    Cantidadreservada smallint                    NULL,
    Fechareservacion  timestamp without time zone NULL,
    ReservacionID     serial                      NOT NULL,
    SucursalID        serial                      NOT NULL,
    Correoelectronico varchar(255)                NULL
)
;

CREATE TABLE Servicios
(
    ServiciosID serial       NOT NULL,
    Servicio    varchar(255) NULL
)
;
INSERT INTO Servicios
VALUES (1, 'ESTACIONAMIENTO'),
       (2, 'VALETPARKING'),
       (3, 'AREAINFANTIL'),
       (4, 'DELIVERY'),
       (5, 'PARALLEVAR'),
       (6, 'AREAAIRELIBRE'),
       (7, 'WIFI'),
       (8, 'RESERVACIONES')
;

CREATE TABLE Sucursal
(
    Aforoactual    smallint     NULL,
    Aforototal     smallint     NULL,
    Nombresucursal varchar(255) NULL,
    Telefono       varchar(255) NULL,
    SucursalID     serial       NOT NULL,
    DomicilioID    serial       NOT NULL,
    NegocioID      serial       NOT NULL
)
;

CREATE TABLE sucursalmedidasSeguridad
(
    MedidasseguridadID serial NOT NULL,
    SucursalID         serial NOT NULL
)
;

CREATE TABLE sucursalservicios
(
    ServiciosID serial NOT NULL,
    SucursalID  serial NOT NULL
)
;

CREATE TABLE Tiponegocio
(
    Tiponegocio   varchar(255) NULL,
    TiponegocioID serial       NOT NULL
)
;
INSERT INTO Tiponegocio
VALUES ('RESTAURANTE', 1),
       ('ESTETICA', 2),
       ('SALONBELLEZA', 3),
       ('BARBERIA', 4),
       ('GIMNASIO', 5),
       ('OTRO', 6)
;

CREATE TABLE Usuario
(
    Codigoautenticacion varchar(255) NULL,
    Contrasenia         varchar(255) NULL,
    Correoelectronico   varchar(255) NOT NULL,
    Edad                smallint     NULL,
    Fechanacimiento     date         NULL,
    Fotoperfil          bytea        NULL,
    Nombrecompleto      varchar(255) NULL,
    Telefono            varchar(255) NULL,
    DomicilioID         serial       NOT NULL,
    AceptadoID          serial       NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */
ALTER TABLE Dia
    ADD CONSTRAINT PK_Dia
        PRIMARY KEY (DiaID)
;

ALTER TABLE Domicilio
    ADD CONSTRAINT PK_Domicilio
        PRIMARY KEY (DomicilioID)
;

ALTER TABLE Aceptado
    ADD CONSTRAINT Aceptadoo
        PRIMARY KEY (AceptadoID)
;

ALTER TABLE Favorito
    ADD CONSTRAINT PK_Favorito
        PRIMARY KEY (SucursalID, Correoelectronico)
;

ALTER TABLE Horario
    ADD CONSTRAINT PK_Horario
        PRIMARY KEY (HorarioID)
;

ALTER TABLE Medidasseguridad
    ADD CONSTRAINT PK_Medidasseguridad
        PRIMARY KEY (MedidasseguridadID)
;

ALTER TABLE Negocio
    ADD CONSTRAINT PK_Negocio
        PRIMARY KEY (NegocioID)
;

ALTER TABLE Opinion
    ADD CONSTRAINT PK_Opinion
        PRIMARY KEY (Correoelectronico, SucursalID)
;

ALTER TABLE Reservacion
    ADD CONSTRAINT PK_Reservacion
        PRIMARY KEY (ReservacionID)
;

ALTER TABLE Servicios
    ADD CONSTRAINT PK_Servicios
        PRIMARY KEY (ServiciosID)
;

ALTER TABLE Sucursal
    ADD CONSTRAINT PK_Sucursal
        PRIMARY KEY (SucursalID)
;

ALTER TABLE sucursalmedidasSeguridad
    ADD CONSTRAINT PK_sucursalmedidasSeguridad
        PRIMARY KEY (MedidasseguridadID, SucursalID)
;

ALTER TABLE sucursalservicios
    ADD CONSTRAINT PK_sucursalservicios
        PRIMARY KEY (ServiciosID, SucursalID)
;

ALTER TABLE Tiponegocio
    ADD CONSTRAINT PK_Tiponegocio
        PRIMARY KEY (TiponegocioID)
;

ALTER TABLE Usuario
    ADD CONSTRAINT PK_Usuario
        PRIMARY KEY (Correoelectronico)
;

/* Create Foreign Key Constraints */

ALTER TABLE Usuario
    ADD CONSTRAINT FK_Domicilio_Usuario
        FOREIGN KEY (DomicilioID) REFERENCES Domicilio (DomicilioID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Favorito
    ADD CONSTRAINT FK_favorito_sucursal
        FOREIGN KEY (SucursalID) REFERENCES Sucursal (SucursalID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Favorito
    ADD CONSTRAINT FK_favorito_usuario
        FOREIGN KEY (Correoelectronico) REFERENCES Usuario (Correoelectronico) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Horario
    ADD CONSTRAINT FK_Horario_Dia
        FOREIGN KEY (DiaID) REFERENCES Dia (DiaID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Horario
    ADD CONSTRAINT FK_Horario_Sucursal
        FOREIGN KEY (SucursalID) REFERENCES Sucursal (SucursalID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Negocio
    ADD CONSTRAINT FK_Negocio_Tiponegocio
        FOREIGN KEY (TiponegocioID) REFERENCES Tiponegocio (TiponegocioID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Negocio
    ADD CONSTRAINT FK_Negocio_Usuario
        FOREIGN KEY (CorreoelectronicoUsuario) REFERENCES Usuario (Correoelectronico) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Opinion
    ADD CONSTRAINT FK_opinion_usuario
        FOREIGN KEY (Correoelectronico) REFERENCES Usuario (Correoelectronico) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Opinion
    ADD CONSTRAINT FK_opinion_sucursal
        FOREIGN KEY (SucursalID) REFERENCES Sucursal (SucursalID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reservacion
    ADD CONSTRAINT FK_reservacion_sucursal
        FOREIGN KEY (SucursalID) REFERENCES Sucursal (SucursalID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Reservacion
    ADD CONSTRAINT FK_reservacion_usuario
        FOREIGN KEY (Correoelectronico) REFERENCES Usuario (Correoelectronico) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Sucursal
    ADD CONSTRAINT FK_Sucursal_Domicilio
        FOREIGN KEY (DomicilioID) REFERENCES Domicilio (DomicilioID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Sucursal
    ADD CONSTRAINT FK_Sucursal_Negocio
        FOREIGN KEY (NegocioID) REFERENCES Negocio (NegocioID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sucursalmedidasSeguridad
    ADD CONSTRAINT FK_sucursalmedidasSeguridad_medidasSeguridad
        FOREIGN KEY (MedidasseguridadID) REFERENCES Medidasseguridad (MedidasseguridadID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sucursalmedidasSeguridad
    ADD CONSTRAINT FK_sucursalmedidasSeguridad_sucursal
        FOREIGN KEY (SucursalID) REFERENCES Sucursal (SucursalID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sucursalservicios
    ADD CONSTRAINT FK_sucursalservicios_servicios
        FOREIGN KEY (ServiciosID) REFERENCES Servicios (ServiciosID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sucursalservicios
    ADD CONSTRAINT FK_sucursalservicios_sucursal
        FOREIGN KEY (SucursalID) REFERENCES Sucursal (SucursalID) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Usuario
    ADD CONSTRAINT FK_Usuario_Aceptado
        FOREIGN KEY (AceptadoID) REFERENCES Aceptado (AceptadoID) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
