# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response200_paginacion import InlineResponse200Paginacion  # noqa: F401,E501
from swagger_server.models.negocio_array import NegocioArray  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, paginacion: InlineResponse200Paginacion=None, resultados: List[NegocioArray]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param paginacion: The paginacion of this InlineResponse200.  # noqa: E501
        :type paginacion: InlineResponse200Paginacion
        :param resultados: The resultados of this InlineResponse200.  # noqa: E501
        :type resultados: List[NegocioArray]
        """
        self.swagger_types = {
            'paginacion': InlineResponse200Paginacion,
            'resultados': List[NegocioArray]
        }

        self.attribute_map = {
            'paginacion': 'paginacion',
            'resultados': 'resultados'
        }
        self._paginacion = paginacion
        self._resultados = resultados

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def paginacion(self) -> InlineResponse200Paginacion:
        """Gets the paginacion of this InlineResponse200.


        :return: The paginacion of this InlineResponse200.
        :rtype: InlineResponse200Paginacion
        """
        return self._paginacion

    @paginacion.setter
    def paginacion(self, paginacion: InlineResponse200Paginacion):
        """Sets the paginacion of this InlineResponse200.


        :param paginacion: The paginacion of this InlineResponse200.
        :type paginacion: InlineResponse200Paginacion
        """

        self._paginacion = paginacion

    @property
    def resultados(self) -> List[NegocioArray]:
        """Gets the resultados of this InlineResponse200.


        :return: The resultados of this InlineResponse200.
        :rtype: List[NegocioArray]
        """
        return self._resultados

    @resultados.setter
    def resultados(self, resultados: List[NegocioArray]):
        """Sets the resultados of this InlineResponse200.


        :param resultados: The resultados of this InlineResponse200.
        :type resultados: List[NegocioArray]
        """

        self._resultados = resultados
