# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorDetail(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, campo: str=None, valor: str=None, problema: str=None, localizacion: str=None):  # noqa: E501
        """ErrorDetail - a model defined in Swagger

        :param campo: The campo of this ErrorDetail.  # noqa: E501
        :type campo: str
        :param valor: The valor of this ErrorDetail.  # noqa: E501
        :type valor: str
        :param problema: The problema of this ErrorDetail.  # noqa: E501
        :type problema: str
        :param localizacion: The localizacion of this ErrorDetail.  # noqa: E501
        :type localizacion: str
        """
        self.swagger_types = {
            'campo': str,
            'valor': str,
            'problema': str,
            'localizacion': str
        }

        self.attribute_map = {
            'campo': 'campo',
            'valor': 'valor',
            'problema': 'problema',
            'localizacion': 'localizacion'
        }
        self._campo = campo
        self._valor = valor
        self._problema = problema
        self._localizacion = localizacion

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorDetail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_detail of this ErrorDetail.  # noqa: E501
        :rtype: ErrorDetail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def campo(self) -> str:
        """Gets the campo of this ErrorDetail.

        JSON Puntero al campo con error si está en el cuerpo, en caso contrario, nombre del parámetro de ruta o parámetro de consulta  # noqa: E501

        :return: The campo of this ErrorDetail.
        :rtype: str
        """
        return self._campo

    @campo.setter
    def campo(self, campo: str):
        """Sets the campo of this ErrorDetail.

        JSON Puntero al campo con error si está en el cuerpo, en caso contrario, nombre del parámetro de ruta o parámetro de consulta  # noqa: E501

        :param campo: The campo of this ErrorDetail.
        :type campo: str
        """

        self._campo = campo

    @property
    def valor(self) -> str:
        """Gets the valor of this ErrorDetail.

        Valor del campo erróneo  # noqa: E501

        :return: The valor of this ErrorDetail.
        :rtype: str
        """
        return self._valor

    @valor.setter
    def valor(self, valor: str):
        """Sets the valor of this ErrorDetail.

        Valor del campo erróneo  # noqa: E501

        :param valor: The valor of this ErrorDetail.
        :type valor: str
        """

        self._valor = valor

    @property
    def problema(self) -> str:
        """Gets the problema of this ErrorDetail.

        Motivo del error  # noqa: E501

        :return: The problema of this ErrorDetail.
        :rtype: str
        """
        return self._problema

    @problema.setter
    def problema(self, problema: str):
        """Sets the problema of this ErrorDetail.

        Motivo del error  # noqa: E501

        :param problema: The problema of this ErrorDetail.
        :type problema: str
        """

        self._problema = problema

    @property
    def localizacion(self) -> str:
        """Gets the localizacion of this ErrorDetail.

        La ubicación del campo en el error, ya sea consulta, ruta o cuerpo. Si este campo no está presente, el valor predeterminado es cuerpo.  # noqa: E501

        :return: The localizacion of this ErrorDetail.
        :rtype: str
        """
        return self._localizacion

    @localizacion.setter
    def localizacion(self, localizacion: str):
        """Sets the localizacion of this ErrorDetail.

        La ubicación del campo en el error, ya sea consulta, ruta o cuerpo. Si este campo no está presente, el valor predeterminado es cuerpo.  # noqa: E501

        :param localizacion: The localizacion of this ErrorDetail.
        :type localizacion: str
        """

        self._localizacion = localizacion
