# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200Paginacion(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total: float=None, salto: float=None, limite: float=None):  # noqa: E501
        """InlineResponse200Paginacion - a model defined in Swagger

        :param total: The total of this InlineResponse200Paginacion.  # noqa: E501
        :type total: float
        :param salto: The salto of this InlineResponse200Paginacion.  # noqa: E501
        :type salto: float
        :param limite: The limite of this InlineResponse200Paginacion.  # noqa: E501
        :type limite: float
        """
        self.swagger_types = {
            'total': float,
            'salto': float,
            'limite': float
        }

        self.attribute_map = {
            'total': 'total',
            'salto': 'salto',
            'limite': 'limite'
        }
        self._total = total
        self._salto = salto
        self._limite = limite

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Paginacion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_paginacion of this InlineResponse200Paginacion.  # noqa: E501
        :rtype: InlineResponse200Paginacion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> float:
        """Gets the total of this InlineResponse200Paginacion.

        La cantidad total de resultados  # noqa: E501

        :return: The total of this InlineResponse200Paginacion.
        :rtype: float
        """
        return self._total

    @total.setter
    def total(self, total: float):
        """Sets the total of this InlineResponse200Paginacion.

        La cantidad total de resultados  # noqa: E501

        :param total: The total of this InlineResponse200Paginacion.
        :type total: float
        """

        self._total = total

    @property
    def salto(self) -> float:
        """Gets the salto of this InlineResponse200Paginacion.

        La cantidad de resultados saltados  # noqa: E501

        :return: The salto of this InlineResponse200Paginacion.
        :rtype: float
        """
        return self._salto

    @salto.setter
    def salto(self, salto: float):
        """Sets the salto of this InlineResponse200Paginacion.

        La cantidad de resultados saltados  # noqa: E501

        :param salto: The salto of this InlineResponse200Paginacion.
        :type salto: float
        """

        self._salto = salto

    @property
    def limite(self) -> float:
        """Gets the limite of this InlineResponse200Paginacion.

        La cantidad de resultados limitados en la respuesta  # noqa: E501

        :return: The limite of this InlineResponse200Paginacion.
        :rtype: float
        """
        return self._limite

    @limite.setter
    def limite(self, limite: float):
        """Sets the limite of this InlineResponse200Paginacion.

        La cantidad de resultados limitados en la respuesta  # noqa: E501

        :param limite: The limite of this InlineResponse200Paginacion.
        :type limite: float
        """

        self._limite = limite
